# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: Mzk4ZmZkZWZkNjY3ODAwYzc2ZWVkMjkxZmU2N2ZiM2I1MzU3Yzc0MGM4ZWRkOTI5MjFlYjUwYTI0YTJjMzE4OTEyOTYwMWJiOGZlZjk1MzBlYzJkZjM1NzVjMTg3YTQ5ZDAyMDI4ZDcyMTdhMDU3ZDYxZWU0NGUyNjk1YTZjZjE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
